version: '3.8'

services:
  websocket-service:
    build:
      context: ./backend
    container_name: messenger-backend
    image: heiligetomate/messenger-backend:latest
    ports:
      - "6789:6789"

  frontend:
    build:
      context: ./frontend
    container_name: messenger-frontend
    image: heiligetomate/messenger-frontend:latest
    ports:
      - "8080:80"
    depends_on:
      - websocket-service
    environment:
      - SERVICE_URL=ws://websocket-service:6789

  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - ./dbinit/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

volumes:
  postgres-data:
  dbinit: