version: '3.8'

services:
  websocket-service:
    build:
      context: ./backend
    container_name: messenger-backend
    image: heiligetomate/messenger-backend:latest
    ports:
      - "6789:6789"

  frontend:
    build:
      context: ./frontend
    container_name: messenger-frontend
    image: heiligetomate/messenger-frontend:latest
    ports:
      - "8080:80"
    depends_on:
      - websocket-service
    environment:
      - SERVICE_URL=ws://websocket-service:6789
